name: 'Make Dockerfile'
description: 'Make Odoo Dockerfile'
branding:
  icon: 'code'
  color: 'green'
inputs:
  workdir:
    description: 'Workdir'
    type: string
    required: false
    default: /github/workspace
  filename:
    description: 'Filename'
    type: string
    required: false
    default: Dockerfile
  base:
    description: 'Base Image'
    type: string
    required: true
  dev:
    description: 'Dev mode'
    type: string
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.workdir }}
    - ${{ inputs.filename }}
    - ${{ inputs.base }}
    - ${{ inputs.dev }}