name: 'Make Dockerfile'
description: 'Make Odoo Dockerfile'
branding:
  icon: 'code'
  color: 'green'
inputs:
  args:
    description: 'Args'
    type: string
    required: true
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}